const HTTP_STATUS = {
  BAD_REQUEST: 400,
  BAD_GATEWAY: 502,
  INTERNAL_SERVER_ERROR: 500,
};

const CONTENT_TYPE = {
  JSON: "application/json",
  FORM_URLENCODED: "application/x-www-form-urlencoded",
};

const VOLC_SUCCESS_CODE = 10000;
const JSON_SNIPPET_LENGTH = 200;
const VISUAL_RAW_SNIPPET_LENGTH = 500;

const DEFAULT_IMAGE_SIZE = "2K";
const DEFAULT_VIDEO_RATIO = "16:9";
const DEFAULT_VIDEO_DURATION_SECONDS = 5;
const DEFAULT_IMAGE_COUNT = 1;

const CHAT_COMPLETION = {
  MAX_TOKENS: 512,
  TEMPERATURE: 0.1,
};

const AIGC_CONFIDENCE = {
  MIN: 0,
  LOW_RISK_THRESHOLD: 0.5,
  HIGH_RISK_THRESHOLD: 0.9,
  MAX: 1,
};

const VOLC_FACE_SWAP_2 = {
  ACTION: "FaceSwap",
  VERSION: "2020-08-26",
  ACTION_ID: "faceswap",
  MODEL_VERSION: "2.0",
};

const VOLC_VISUAL = {
  VERSION: "2022-08-31",
  FACE_SWAP_ACTION: "CVProcess",
  FACE_SWAP_REQ_KEY: "face_swap3_6",
  FACE_SWAP_FACE_TYPE: "area",
  FACE_SWAP_SOURCE_LOCATION: 1,
  FACE_SWAP_TEMPLATE_LOCATION: 1,
  SEEDEDIT_SUBMIT_ACTION: "CVSync2AsyncSubmitTask",
  SEEDEDIT_GET_RESULT_ACTION: "CVSync2AsyncGetResult",
  SEEDEDIT_REQ_KEY: "seededit_v3.0",
  SEEDEDIT_DEFAULT_SEED: -1,
  SEEDEDIT_DEFAULT_SCALE: 0.5,
  SEEDEDIT_MIN_SEED: -1,
  SEEDEDIT_MAX_SEED: 2147483647,
  SEEDEDIT_MIN_SCALE: 0,
  SEEDEDIT_MAX_SCALE: 1,
};

const POLLING = {
  ARK_VIDEO_MAX_ATTEMPTS: 120,
  ARK_VIDEO_INTERVAL_MS: 3000,
  SEEDEDIT_MAX_ATTEMPTS: 60,
  SEEDEDIT_INTERVAL_MS: 2000,
};

const MODELSCOPE = {
  DEFAULT_FRAMES: 16,
  MIN_FRAMES: 4,
  MAX_FRAMES: 24,
  DEFAULT_INFERENCE_STEPS: 25,
  MIN_INFERENCE_STEPS: 10,
  MAX_INFERENCE_STEPS: 50,
};

const ARK_TASK_STATUS = {
  SUCCEEDED: "succeeded",
  FAILED: "failed",
};

const SEEDEDIT_TASK_STATUS = {
  DONE: "done",
  NOT_FOUND: "not_found",
  EXPIRED: "expired",
};

const DEFAULT_FACE_ANIMATION_PROMPT = "让图中人脸做自然的微笑和轻微点头动作";

module.exports = {
  AIGC_CONFIDENCE,
  ARK_TASK_STATUS,
  CHAT_COMPLETION,
  CONTENT_TYPE,
  DEFAULT_FACE_ANIMATION_PROMPT,
  DEFAULT_IMAGE_COUNT,
  DEFAULT_IMAGE_SIZE,
  DEFAULT_VIDEO_DURATION_SECONDS,
  DEFAULT_VIDEO_RATIO,
  HTTP_STATUS,
  JSON_SNIPPET_LENGTH,
  MODELSCOPE,
  POLLING,
  SEEDEDIT_TASK_STATUS,
  VISUAL_RAW_SNIPPET_LENGTH,
  VOLC_FACE_SWAP_2,
  VOLC_SUCCESS_CODE,
  VOLC_VISUAL,
};
